todoapp/urls.py
from django.urls import path

from todoapp import views

app_name = 'todoapp'
urlpatterns = [
    path('', views.add, name='home'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('update/<int:id>/',views.update, name='update'),
    path('cbvhome/', views.TaskListView.as_view(), name='cbvhome'),
    path('cbvdetail/<int:pk>/', views.Taskdetailsview.as_view(), name='cbvdetail'),
    path('cbvupdate/<int:pk>/', views.Taskupdateview.as_view(), name='cbvupdate'),
    path('cbvdelete/<int:pk>/', views.Taskdeleteview.as_view(), name='cbvdelete'),
]

todoproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from todoproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoapp/models.py
from django.db import models
# Create your models here.

class Task(models.Model):
    name = models.CharField(max_length=250)
    priority = models.IntegerField()
    date = models.DateField()
    def __str__(self):
        return self.name

todoapp/forms.py
from django import forms
from . models import Task


class Taskform(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'priority', 'date']

todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from . models import Task
from . forms import Taskform
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView


class TaskListView(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'showtask'

class Taskdetailsview(DetailView):
    model = Task
    template_name = 'details.html'
    context_object_name = 'task'

class Taskupdateview(UpdateView):
    model = Task
    template_name = 'edit.html'
    context_object_name = 'task'
    fields = ('name','priority','date')

    def get_success_url(self):
        return reverse_lazy('cbvdetail',kwargs={'pk':self.object.id})

class Taskdeleteview(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('cbvhome')

# Create your views here.
def add(request):
    showtask = Task.objects.all()
    if request.method == 'POST':
        name = request.POST.get('task','')
        priority = request.POST.get('priority','')
        date = request.POST.get('date','')
        task = Task(name=name,priority=priority,date=date)
        task.save()
    return render(request,'home.html',{'showtask':showtask})
# def detail(request):
#     task = Task.objects.all()
#     return render(request,'details.html',{'task':task})
def delete(request,id):
    if request.method == 'POST':
        task = Task.objects.get(id=id)
        task.delete()
        return redirect('/')
    return render(request,'delete.html')
def update(request,id):
    task = Task.objects.get(id=id)
    f = Taskform(request.POST or None , instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request,'update.html',{'task':task,'form':f})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>base</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="{% static 'style.css' %}" rel="stylesheet">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure the task is done ?</p>
    <button type="submit">confirm</button>
</form>
{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% block content %}

                <div class="shadow card">
                    <div class="card-body">
                        <h5 class="card-title">{{task.name}}</h5>
                        <p><b>{{task.priority}}</b></p>
                        <p><b>{{task.date}}</b></p>
                        <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">Done</a>
                        <a class="btn btn-warning" href="{% url 'todoapp:update' task.id %}">Update</a>
                    </div>
                </div>

{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            <h2>Table update</h2>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Confirm</button>
            </form>

        </div>
    </div>
</div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h2>ToDo</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" class="p-3 shadow">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="task" placeholder="Task name">
                </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="priority" placeholder="Enter your Priority">
                    </div>
                        <div class="form-group">
                            <input type="date" class="form-control" name="date">
                        </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-success">
                            </div>
            </form>
        </div>
            <div class="col-md-6">
                {% for i in showtask %}
                <div class="shadow card">
                    <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
                        <p><b>{{i.priority}}</b></p>
                        <p><b>{{i.date}}</b></p>
                        <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                        <a class="btn btn-warning" href="{% url 'todoapp:update' i.id %}">Update</a>
                    </div>
                </div>
                <br>
                {% endfor %}
            </div>
    </div>
</div>

{% endblock %}

templates/update.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock %}